### ISSUE TITLE
Serverside Crash

### ISSUE THREAD

**Issue by Vyraal1** [Terrails/NetherUtils#6]
https://hastebin.com/eduponejih.sql

Not really sure what was going on here.

**Comment by Terrails** [comment]
I'm not really sure either since this causes no issue with my code (nothing in my code caused that error), I'm pretty sure this is a forge bug because of this line
`Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@58d63b16 from coremod FMLCorePlugin
`
I'm gonna look into it on forge forums.

**Comment by Terrails** [comment]
Just uploaded a file to Curse. I didn't update NetherUtils since it wasn't an issue with that, update to TerraCore-1.12-2.1.11 after it gets approved (Couple of minutes or hours, it all depends on Curse).
